### ISSUE TITLE
Add the possibility to the non-technical people

### ISSUE THREAD

**Issue by loislin** [GraphCMS/Feature-Requests#104]
Scenario:
Assume that I am a non-technical person, and I want to access the schema or even data by entering the public API endpoint (url). Then, I can get the data and schema. I don't know any query syntax about graphql, but I really want to see the data. So it will be perfect, GraphCMS provides me some function that I can click and the data will be shown.

It is also useful for the developers if they want to show others what they store the or event the graph of schema,

**Comment by belazer** [comment]
Hey @loislin! We currently allow downloading the schema by pressing "Download Schema" in the Settings. Downloading Content will become available in the near future since we had to remove it due to changes from our API provider.
