### ISSUE TITLE
Allow to hide fields in UI 

### ISSUE THREAD

**Issue by FrediBach** [GraphCMS/Feature-Requests#16]
It would be nice to have custom hidden fields, especially in combination with webhooks. They are not visible when you create content, but when saved, the webhook would read the just published content and based on its data fill in the hidden field, by calculating based on the data or by calling other services to generate the fields data. This could for example be a weather service that is used to import the weather (into a hidden JSON field) based on the contends date and location field.

**Comment by mlukaszczyk** [comment]
Would you want to just hide the fields from your users in the UI or would you also want to hide them from the API?

**Comment by FrediBach** [comment]
Only from the UI. Wouldn't make much sense if they wouldn't show up in the API.

**Comment by mlukaszczyk** [comment]
Alright, I think that makes sense. We would need to incorporate this feature in the role system though. I will let you know after we had some additional thoughts on this.

**Comment by belazer** [comment]
continued in #81
