### ISSUE TITLE
Optional size limit on text fields

### ISSUE THREAD

**Issue by FrediBach** [GraphCMS/Feature-Requests#17]
For example for an intro field that is used on overview pages and that has limited available size in the UI. For many things automatic limitations such as adding '...' after a specific max count of characters is not a good solution.

**Comment by mlukaszczyk** [comment]
Hey @FrediBach, this feature will most likely be available in Q2 when we will implement custom constraints for fields 👍

**Comment by FrediBach** [comment]
Cool, thanks. :-)

**Comment by tomByrer** [comment]
As an intermediate small improvement, could you add a plain character count?  You'll have to add one sooner or later.

**Comment by mlukaszczyk** [comment]
Hey @tomByrer, that´s a great idea. We will add one this week.

**Comment by d-winter** [comment]
Hey @tomByrer 
I added a simple character count for singleLine, multiLine and slug text fields.
Thanks for your input!
Best
Daniel
