### ISSUE TITLE
Hosted pre-made dummy data?

### ISSUE THREAD

**Issue by tomByrer** [GraphCMS/Feature-Requests#19]
As an engineer who wants to quickly check out the GUI and capability of GraphCMS, I would like to just open and edit an existing dataset rather than start one from scratch.  Maybe your own blog (copy ;) ) or a dummy online store?  I find [swapi-graphql](https://github.com/graphql/swapi-graphql) very convenient to use as a demo.

**Comment by mlukaszczyk** [comment]
Hey @tomByrer, we are currently working on an interactive onboarding and we will add some example projects right after. Furthermore, we are going to implement a templating mechanism for content models so that anyone will be able to create and share content models.
