### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by paales** [GraphCMS/Feature-Requests#21]
Hi there, we're currently building a new site and it would be great if we would get multi-language for 'free'.

Almost all of our sites are required to be multi language and it would be nice if it is possible to be able to translate certain fields from the backend and get the multi language stuff for free when setting up your content models.

~A little background: We're developers from the Netherlands. Almost all of our customers will sell internationally so having the site available in more than one language is essential. In an ideal situation every small company will have a dutch version of their site and an english one. After growth they will include a french one, german one, danish one, etc..~ You guys are from Germany, so you know what i'm talking about 😛 

We've been working with Magento a lot, which has an interesting approach to multi language, which might be useful. Magento implements field-scopes that allows us to define if a field is global or per website (there actually is a third layer, but that isn't relevant).

In Magento there is a global switcher (in the Admin Panel) to switch to a different content-language. Each field has a checkbox which allows you to override this data or use the 'global' data.

This moves the complexity of maintaining a multi language website to the backend instead of cluttering the frontend. This would require some global 'flag' when communicating with GraphQL to set the current scope.

Currently it is possible to do multi language, but that would blow up quite quickly with fields like content_nl, content_en, content_fr, title_nl, title_en, title_fr. If it isn't possible, we might consider setting up a second project, but that would require maintaining two separate schema's, which you don't want.

**Comment by mlukaszczyk** [comment]
Hey @paales, we totally get this and this will definitely be one of our top priorities in Q2, but we haven´t fully specced this out yet. Ideally, CMS users could add a variation of a content entry for each language key. Then you could just use a language key filter. 

Agreed that this is a must have feature. Adding more fields for each language is not a good solution since we currently allow 100 fields per model. This could go terribly wrong. We will try to come up with a seamless solution for i8n.

**Comment by Taube** [comment]
Hi guys, I've been working with EPiServer and i18n to handle translation keys for the Single Page App. The company uses Crowdin to manage the translation and review process and we use their CLI to upload source language keys and download translations that are returned as JSON. An integration with external servies like Crowdin would be a killer feature, especially if it was visualized in the CMS if the fields were translated or not. I can't wait to try out your solution for Multi language support.

**Comment by mlukaszczyk** [comment]
Hey @Taube, sorry for the late response here but we finally scheduled i18n for August.

**Comment by loremdolor** [comment]
@mlukaszczyk  Any news on the multilang front? I cant find anything about it on the official website.

**Comment by mlukaszczyk** [comment]
Hey @loremdolor, we are currently working on this and we hope to ship this in the next 2-4 weeks.

**Comment by mlukaszczyk** [comment]
done: https://graphcms.com/blog/introducing-content-localization
