### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by paales** [GraphCMS/Feature-Requests#22]
Having a good search to search through content would be nice. If we'd go all out we'd like to have wordstemming, splitting of combined words (like you have in german/dutch), ability to specify in which index each word should be etc.

Connecting with a thrid party search indexer would be fine as well, but integrating that is probably a pain (they probably don't offer a GraphQL interface).

**Comment by mlukaszczyk** [comment]
Agreed, that it needed and of actually a standard functionality every CMS should have. It wasn´t high priority for the beta launch but now that someone asks for it, it is 🤓.

**Comment by mlukaszczyk** [comment]
done (:

**Comment by paales** [comment]
Hi @mlukaszczyk,

It seems it's implemented in the backend, issue was regarding a GraphQL API implementation

**Comment by mlukaszczyk** [comment]
Ah got it. Sorry for that! Basic search is possible with filters but something like an Algolia integration would be nice as well.

**Comment by d-winter** [comment]
Hey @paales we rolled out an algolia integration. You can have a look here: https://graphcms.com/blog/algolia-integration-with-graphcms

**Comment by paales** [comment]
Oh nice!
