### ISSUE TITLE
Add link option to rich text editor

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Feature-Requests#24]

**Comment by mlukaszczyk** [comment]
Will do. Also we are going to add the media dialog for the rich and markdown inputs

**Comment by SharadKumar** [comment]
It would be great to have RTE CMS experience, such as Ory http://editor.ory.am/

**Comment by mlukaszczyk** [comment]
Hey @SharadKumar, sorry for the late response here but we will actually add Ory soon!
