### ISSUE TITLE
Developer Environment API Key

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Feature-Requests#26]
**Imagine the following scenario**
You are working on a site that uses GraphCMS for content management and the site is already live but you are working locally to implement new features and so on. However you still use GraphCMS and you actually don't want to push the production API key to the git repo but it is also cumbersome if you need to share privately share the key with all the people in the team for example.

**A possible solution**
Imagine a "Developer Environment API key". This key can be used just like a regular API key with 1 major difference. When creating or updating records they are not created in the production table but in some sort of "shadow" table. GraphCMS knows when the development key is used and will, upon queries, combine the shadow table and the production table to return a correct result for the development environment, while making sure the production data stays the same. This way the development key can be pushed to the git repo without needing to worry about messing up production data and without having to set up 2 graphcms projects for example, or double all the tables.

**Comment by mlukaszczyk** [comment]
Where did my comment go? I swear that I already answered in this thread 😬

Having the chance to create a testing environment is important, totally agree on this. But we think that a better solution would be to allow to fork a project and create a cloned instance. This will also allow you to experiment with breaking changes in our content structure.

**Comment by LiamMartens** [comment]
I never got a comment here until now haha 😂 but yes of course that is also a possibility. Though how would that work with files? Would they be cloned as well? I'm just thinking about what if there is a lot of data then cloning might be quite slow in the first place and might greatly increase the need for storage space. That's why I was thinking about the solution I typed out.

Although cloning would work just fine as well really.

**Comment by mlukaszczyk** [comment]
This shouldn´t be that big of an issue. Assets are stored seperately and linked with the media model of your project. But it could make sense to limit the content of a cloned project. We could, for example, just clone a small subset of the actual data. This should be sufficient of development anyways. 

However, we haven´t really specced this out, but this needs to be done in the near future.
