### ISSUE TITLE
Closing dialogs and messages with Escape key

### ISSUE THREAD

**Issue by worchyld** [GraphCMS/Feature-Requests#29]
I'd like to close dialogs and messages with escape key.  Thanks

**Comment by mlukaszczyk** [comment]
Agreed, it´s annoying. We will enable this again.

**Comment by worchyld** [comment]
This get resolved?

**Comment by mlukaszczyk** [comment]
Hey @worchyld, sorry for the late response, we are currently working on a better issue tracking integration with our other services. Yes we have fixed this already (:

**Comment by worchyld** [comment]
Okay, cool.
