### ISSUE TITLE
Better UI for 1:1 relations

### ISSUE THREAD

**Issue by paales** [GraphCMS/Feature-Requests#33]
Currently the UI for 1:1 relationships is the same as one:many relationships, could be a lot cleaner.

**Comment by mlukaszczyk** [comment]
Hey @paales, we will shortly take a look on how to enhance the UX on relations in general. We will take your feedback into account!

**Comment by belazer** [comment]
The UI will be completely redesigned in the new GraphCMS web app and will take this into account!
