### ISSUE TITLE
WYSIWYG editor with support for images

### ISSUE THREAD

**Issue by paales** [GraphCMS/Feature-Requests#35]
The current WYSIWYG editor is pretty rudimentary in it's features, only the most basic HTML tags, would be nice if it would allow you to upload images in some way.

**Comment by mlukaszczyk** [comment]
This feature is almost ready. We will roll it out with the new systems API in the next week. It will allow direct HTML manipulation and input of images from your media library.

**Comment by paales** [comment]
Awesome!

**Comment by mlukaszczyk** [comment]
done (:
