### ISSUE TITLE
Choose columns to display

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Feature-Requests#36]
A way to choose what columns to display in the content table overview.
Directus does this pretty cleanly

![output](https://user-images.githubusercontent.com/5265324/27730039-374d70b4-5d88-11e7-805a-f70d906f1caa.gif)

**Comment by mlukaszczyk** [comment]
That's exactly how we plan to do it. Should land in August and will also have sorting.

**Comment by mlukaszczyk** [comment]
A little late, but will land in the next release: https://github.com/GraphCMS/Feature-Requests/issues/23
