### ISSUE TITLE
Allow showing a field value in  a relation field

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Feature-Requests#37]
![deepinscreenshot20170630113638](https://user-images.githubusercontent.com/5265324/27730090-6946090a-5d88-11e7-9590-e6d69d1fd5b8.png)
This works but is not quite glanceable. To make content models easier to glance over being able to display a value from the related table would be great.

**Comment by mlukaszczyk** [comment]
Do you have anything concrete in mind?

**Comment by LiamMartens** [comment]
It would be cool if you were able to select an actual field value to show next to it or something.
Imagine a content model that has a relation to another model called Post or something and then it would show the titles of the posts instead of the icon thingy

**Comment by mlukaszczyk** [comment]
Makes sense, we will give it some thoughts!

**Comment by belazer** [comment]
This will also be changed in the new web app!
