### ISSUE TITLE
UI Button distinctions aren't clear

### ISSUE THREAD

**Issue by jkauszler** [GraphCMS/Feature-Requests#39]
<img width="427" alt="screen shot 2017-08-01 at 9 29 03 pm" src="https://user-images.githubusercontent.com/3312031/28853712-7c9169be-7700-11e7-88ba-235470f66ed4.png">

The button labeled "Show system fields" is difficult to distinguish as a button between the other tags/labels next to it. It wasn't clear until after clicking everything that, when clicked on that piece of UI, I would receive some sort of reaction.

**Comment by mlukaszczyk** [comment]
Hey @jkauszler,

thanks for the feedback! We will try to apply it in the next UI revision. Totally understand your point.

Best,

Michael

**Comment by mlukaszczyk** [comment]
Will close this ticket for now but we are going to incorporate this feedback in the upcoming UI overhaul.
