### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by sandergo90** [GraphCMS/Feature-Requests#40]
Hi!

This project is looking very nice but it would be even better if you can open source the project. 

I think a lot of us would like to contribute to the project to make it awesome.

You are already on github for requests, so why not make it open source ? ;)

Cheers!

**Comment by mlukaszczyk** [comment]
Hey @sandergo90 👋

Thanks for the feedback! We are thinking about this actually, but we would probably consider open sourcing parts of the system that would actually make sense for the community. There are a lot of components and moving parts in the whole infrastructure that depend on other 3rd party services that aren't open source as well. We definitely see the benefits of this, on the other hand, we try to build a sustainable business. We are aware that you can do this with an open source strategy as well. We will keep this in the internal discussion for sure!

Kind regards,

Michael

**Comment by sandergo90** [comment]
Hi @mlukaszczyk,

Thanks for the quick response! 

We're looking forward to the open sourcing part ❤️ 

Keep us posted 😉 

Cheers!
