### ISSUE TITLE
add Region option or CDN

### ISSUE THREAD

**Issue by tgfjt** [GraphCMS/Feature-Requests#42]
Hi!

APIs are only provided from `eu-west-1` region now.
but it might be far from some places. e.g. JAPAN...

We would be happy to be provided CDN or other regions.

**Comment by mlukaszczyk** [comment]
We are going to add support for the regions US-West and Asia Pacific (Tokyo) (:

**Comment by tgfjt** [comment]
I can't wait!!

**Comment by mlukaszczyk** [comment]
One thing is though that you won't be able to easily switch datacenters in your project, but no worries on this, we will help you with the migration as soon as this is ready!

**Comment by d-winter** [comment]
We added region support last week. See here for a guide: https://graphcms.com/blog/supporting-multiple-regions

**Comment by tgfjt** [comment]
**SUPER**
