### ISSUE TITLE
auth0 blocked by Privacy Badger

### ISSUE THREAD

**Issue by buckle2000** [GraphCMS/Feature-Requests#46]
https://app.graphcms.com/login

![default](https://user-images.githubusercontent.com/10850402/31122798-d7499a70-a86f-11e7-8641-9830da936ea1.png)

I don't know how to contact "support", though.

Cannot load scripts.
![default](https://user-images.githubusercontent.com/10850402/31122816-ee26d3de-a86f-11e7-9288-6bbf872356dc.png)

**Comment by mlukaszczyk** [comment]
Hey! We don't see any issues. Is this still happening for you? What browser are you using?

**Comment by buckle2000** [comment]
OK I found the reason. Privacy Badger from eff.org blocked `*.auth0.com`.
