### ISSUE TITLE
Author field

### ISSUE THREAD

**Issue by tremby** [GraphCMS/Feature-Requests#49]
I was surprised to find entries don't appear to have an author field, showing which GraphCMS added the entry.

**Comment by mlukaszczyk** [comment]
We skipped this at first as we want to incorporate this within the new user system we plan for the next major milestone. The new user and permission system will also allow user authentication in your sites and apps (on a side note)

**Comment by mlukaszczyk** [comment]
closed due to: https://github.com/GraphCMS/Feature-Requests/issues/75
