### ISSUE TITLE
In multi-step dialogs allow skipping to different pages

### ISSUE THREAD

**Issue by tremby** [GraphCMS/Feature-Requests#51]
In multi-step dialogs where values already exist, such as the "edit field" dialog, clicking on the step headers (1 Appearance, 2 Field settings, 3 Additional Settings) should take you to those pages.

Incidentally, while I notice it, be consistent with the capitalization. "Field settings" vs "Additional Settings".

**Comment by belazer** [comment]
This will be completely redesigned in the new web app!
