### ISSUE TITLE
Add a bug report button inside the web app

### ISSUE THREAD

**Issue by toshi38** [GraphCMS/Feature-Requests#53]
It'd be nice to have a bug report button inside the web app where you could type some steps to reproduce an issue, (optionally) upload a screen shot or video, and describe the problem.  Ideally the tool would also (optionally) pickup the logs to make it easier to debug the problems.

**Comment by mlukaszczyk** [comment]
That would be great and I think there are already some good solutions for this out there. But don't you think that the intercom is sufficient for this?

**Comment by toshi38** [comment]
Depends on if you can pickup logs in a decent way... a few projects I've worked on have had this functionality and logs don't lie... it makes it way easier to see what users actually did and to collect debugging data and such (like dumping state or w/e on log) so you can reproduce and fix the issues quicker....

**Comment by mlukaszczyk** [comment]
A simple version of this is now deployed and integrated into our error messages / intercom widget https://github.com/GraphCMS/Feature-Requests/issues/60
