### ISSUE TITLE
Specify a "Title" field

### ISSUE THREAD

**Issue by toshi38** [GraphCMS/Feature-Requests#58]
Currently when you edit something you can't really tell what entry you're editing.

Sure it shows: 
![image](https://user-images.githubusercontent.com/13830694/32146669-322ea2ee-bcdb-11e7-98e4-1b87a53800f9.png)

But that isn't really useful as I didn't specify `cj9c...`

What would be useful is if I could mark one of the fields in my model as being the "Title" of the object to be shown on various places within the GUI.

**Comment by RobertJames** [comment]
Surely if you're already editing something you can already view the existing title?

**Comment by toshi38** [comment]
Not when you scroll down/view different areas.  It'd be nice to have something pinned that's meaningful.

Especially if you have a bunch of relation fields and such and all you can see in the current window is:
![image](https://user-images.githubusercontent.com/13830694/32165197-4460fd04-bd62-11e7-92f5-de93bffc6df3.png)

It's particularity annoying when you get distracted or are trying to multi task and forget exactly where you are ;)

**Comment by krawaller** [comment]
+1 for this. Sure you can find out what item it is if you scroll around, but it would be nice to always have that info on screen.

**Comment by toshi38** [comment]
This also extends to relations... it'd be nice to be able to see some kind of "nice" view of relations on the table page instead of just knowing that it has two related <whatevers>

**Comment by mlukaszczyk** [comment]
Done. You can now specify a title field in the model config (-> edit model). We still need a good way for previewing relations. 

See also https://github.com/GraphCMS/Feature-Requests/issues/37
