### ISSUE TITLE
Permissions for AuthTokens

### ISSUE THREAD

**Issue by d-winter** [GraphCMS/Feature-Requests#6]
In order to store auth tokens on the client side, we will introduce a read only permission level on auth tokens. 
This will be analogous for create, update and delete.

**Comment by mlukaszczyk** [comment]
This will be closed in favor to our new permission system (short guide here: https://graphcms.com/docs/guides/Using_Permissions/)

**Comment by tremby** [comment]
I'm confused by this. On [this doc page](https://graphcms.com/docs/guides/Using_permanent_auth_tokens/) it says

> We will soon release a feature that will allow you to create read-only tokens, so even if someone gains access to such a token, your data will be safe from manipulation.

That sounds like this feature, is it not?

Is it possible to make one auth token with fine-grained write permissions, but another one with read-only?

**Comment by mlukaszczyk** [comment]
Not yet, but this is actually still in graphcools pipeline. We are built on top of them.

**Comment by tremby** [comment]
I believe this means for now that I can't run a GraphQL client on the client side of a website (read-only), and then also have an admin panel with write access to the same GraphCMS repository.

**Comment by mlukaszczyk** [comment]
Yes, except you would use a permanent auth token which bypasses the permission system. The token shouldn't be exposed on the client though.

**Comment by tremby** [comment]
I'm still confused.

Are you saying it is or is not possible?

If a GraphQL client such as Apollo is to run on the client side, all of its code and configuration is by definition exposed to the user. So if an auth token is minted for this, it must be restricted to read-only access.

But then how can I have another auth token for my back-end code, which maybe has some maintenance tools which, say, deletes old entries, or creates new entries from data collected from another source?

**Comment by mlukaszczyk** [comment]
It's not possible now as permanent auth tokens won't allow control over read and write access. I'm currently travelling but you seem to provide valuable feedback. Would you be in for a call next week so we can talk through all your cases?
