### ISSUE TITLE
Contentful project importer

### ISSUE THREAD

**Issue by mlukaszczyk** [GraphCMS/Feature-Requests#62]
We are building a Contentful importer tool so users can migrate their projects over to GraphCMS.

**Comment by brandonmp** [comment]
i just did this. maybe this'll help

https://github.com/contentful-labs/cf-graphql

**Comment by mlukaszczyk** [comment]
Thanks! But this is almost ready and will be rolled out soon.

**Comment by mlukaszczyk** [comment]
done https://graphcms.com/blog/contentful-importer
