### ISSUE TITLE
Show number of items being deleted

### ISSUE THREAD

**Issue by toshi38** [GraphCMS/Feature-Requests#88]
![image](https://user-images.githubusercontent.com/13830694/32851496-632c7da0-ca35-11e7-83b3-b82567df49f2.png)

Such a message makes me really paranoid if I'm deleting "1" item ... or "10" if it said how many it was deleting I would know if its the correct number or not.

**Comment by mlukaszczyk** [comment]
Makes sense to me.

**Comment by toshi38** [comment]
It'd also be nice to give some overview of which items are being deleted :)
