### ISSUE TITLE
Hide Relation Fields

### ISSUE THREAD

**Issue by eruby94** [GraphCMS/Feature-Requests#91]
Similar to hiding system fields, hiding relation fields would be helpful for isolating a model's direct field:value pairs. Mostly, this would be helpful following the implementation of custom asset fields, since the list of relations can quickly get lengthy.

**Comment by eruby94** [comment]
https://github.com/GraphCMS/Feature-Requests/issues/71

**Comment by mlukaszczyk** [comment]
Thats a great idea! Will discuss it with the team but I definitely see the UX improvements.

**Comment by Corvax-Fisher** [comment]
This feature is live now.
